server:
  port: 8081

spring:
  profiles: default
  cloud:
    consul:
      host: 192.168.120.14
      port: 8500
      discovery:
        prefer-ip-address: true
---
spring:
  application:
    name: grpc-client